# Generated by Django 5.2.8 on 2025-12-05 18:30

from django.db import migrations


ARTICLES = {
    'USER1': [
        {
            'header': 'user1_article1_header',
            'text': 'user1_article1_text',
            'comments': [
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment1',
                },
                {
                    'owner': 'USER2',
                    'comment': 'user2_comment1',
                },
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment2',
                },
            ]
        },
        {
            'header': 'user1_article1_header',
            'text': 'user1_article1_text',
            'comments': [
                {
                    'owner': 'USER_EDITOR',
                    'comment': 'user_editor_comment1',
                },
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment1',
                },
                {
                    'owner': 'USER_MODERATOR_EDITOR',
                    'comment': 'user_moderator_editor_comment2',
                },
            ]
        },
    ],
    'USER2': [
        {
            'header': 'user2_article1_header',
            'text': 'user2_article1_text',
            'comments': [
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment1',
                },
                {
                    'owner': 'USER2',
                    'comment': 'user2_comment1',
                },
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment2',
                },
            ]
        },
        {
            'header': 'user2_article1_header',
            'text': 'user2_article1_text',
            'comments': [
                {
                    'owner': 'USER_EDITOR',
                    'comment': 'user_editor_comment1',
                },
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment1',
                },
                {
                    'owner': 'USER_MODERATOR_EDITOR',
                    'comment': 'user_moderator_editor_comment2',
                },
            ]
        },
    ],
    'USER_EDITOR': [
        {
            'header': 'user1_article1_header',
            'text': 'user1_article1_text',
            'comments': [
                {
                    'owner': 'USER2',
                    'comment': 'user2_comment1',
                },
            ]
        },
    ],
}


def populate_data(apps, schema_editor):
    UserModel = apps.get_model('users', 'User')
    ArticleModel = apps.get_model('article', 'Article')
    CommentModel = apps.get_model('article', 'Comment')

    users = UserModel.objects.all()
    users_map = {user.first_name: user for user in users}

    articles = []
    comments = []
    for user_name, articles_list in ARTICLES.items():
        for p in articles_list:
            article_obj = ArticleModel(
                owner=users_map[user_name],
                header=p['header'],
                text=p['text']
            )
            articles.append(article_obj)

            comments += [
                CommentModel(
                    article=article_obj,
                    owner=users_map[comment['owner']],
                    comment=comment['comment']
                )
                for comment in p['comments']
            ]

    ArticleModel.objects.bulk_create(articles)
    CommentModel.objects.bulk_create(comments)


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('users', '0003_auto_20251205_1720')
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop)
    ]
