# Generated by Django 5.2.8 on 2025-12-05 18:03

from django.db import migrations


POSTS = {
    'USER1': [
        {
            'header': 'user1_post1_header',
            'text': 'user1_post1_text',
            'comments': [
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment1',
                },
                {
                    'owner': 'USER2',
                    'comment': 'user2_comment1',
                },
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment2',
                },
            ]
        },
        {
            'header': 'user1_post1_header',
            'text': 'user1_post1_text',
            'comments': [
                {
                    'owner': 'USER_EDITOR',
                    'comment': 'user_editor_comment1',
                },
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment1',
                },
                {
                    'owner': 'USER_MODERATOR_EDITOR',
                    'comment': 'user_moderator_editor_comment2',
                },
            ]
        },
    ],
    'USER2': [
        {
            'header': 'user2_post1_header',
            'text': 'user2_post1_text',
            'comments': [
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment1',
                },
                {
                    'owner': 'USER2',
                    'comment': 'user2_comment1',
                },
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment2',
                },
            ]
        },
        {
            'header': 'user2_post1_header',
            'text': 'user2_post1_text',
            'comments': [
                {
                    'owner': 'USER_EDITOR',
                    'comment': 'user_editor_comment1',
                },
                {
                    'owner': 'USER1',
                    'comment': 'user1_comment1',
                },
                {
                    'owner': 'USER_MODERATOR_EDITOR',
                    'comment': 'user_moderator_editor_comment2',
                },
            ]
        },
    ],
    'USER_EDITOR': [
        {
            'header': 'user1_post1_header',
            'text': 'user1_post1_text',
            'comments': [
                {
                    'owner': 'USER2',
                    'comment': 'user2_comment1',
                },
            ]
        },
    ],
}


def populate_data(apps, schema_editor):
    UserModel = apps.get_model('users', 'User')
    PostModel = apps.get_model('posts', 'Post')
    CommentModel = apps.get_model('posts', 'Comment')

    users = UserModel.objects.all()
    users_map = {user.first_name: user for user in users}

    posts = []
    comments = []
    for user_name, posts_list in POSTS.items():
        for p in posts_list:
            post_obj = PostModel(
                owner=users_map[user_name],
                header=p['header'],
                text=p['text']
            )
            posts.append(post_obj)

            comments += [
                CommentModel(
                    post=post_obj,
                    owner=users_map[comment['owner']],
                    comment=comment['comment']
                )
                for comment in p['comments']
            ]

    PostModel.objects.bulk_create(posts)
    CommentModel.objects.bulk_create(comments)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0003_auto_20251205_1720')
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop)
    ]
