# Generated by Django 5.2.8 on 2025-12-02 13:42

from django.db import migrations

from ..enums import ElementEnum, RoleEnum


def populate_data(apps, schema_editor):
    ElementModel = apps.get_model('authorization', 'Element')
    RoleModel = apps.get_model('authorization', 'Role')

    ElementModel.objects.bulk_create(
        [ElementModel(name=element.value) for element in ElementEnum]
    )
    RoleModel.objects.bulk_create(
        [RoleModel(name=role.value) for role in RoleEnum]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop)
    ]
