# Generated by Django 5.2.8 on 2025-12-04 11:28

from django.db import migrations

from ..enums import ElementEnum, RoleEnum


READ       = 0b00000001
READ_ALL   = 0b00000010
CREATE     = 0b00000100
UPDATE     = 0b00001000
UPDATE_ALL = 0b00010000
DELETE     = 0b00100000
DELETE_ALL = 0b01000000

FULL_READ = READ | READ_ALL
ALL_PERMISSIONS = READ | READ_ALL | CREATE | UPDATE | UPDATE_ALL | DELETE | DELETE_ALL

PERMISSIONS = {
    RoleEnum.ADMIN.value: {
        ElementEnum.ARTICLE.value: ALL_PERMISSIONS,
        ElementEnum.ARTICLE.value: ALL_PERMISSIONS,
        ElementEnum.COMMENTS.value: ALL_PERMISSIONS,
        ElementEnum.POSTS.value: ALL_PERMISSIONS,
        ElementEnum.PROFILE.value: ALL_PERMISSIONS,
        ElementEnum.USER.value: ALL_PERMISSIONS,
    },
    RoleEnum.EDITOR.value: {
        ElementEnum.ARTICLE.value: FULL_READ | UPDATE_ALL,
        ElementEnum.COMMENTS.value: FULL_READ,
        ElementEnum.POSTS.value: FULL_READ,
        ElementEnum.PROFILE.value: FULL_READ,
        ElementEnum.USER.value: READ,
    },
    RoleEnum.GUEST.value: {
        ElementEnum.ARTICLE.value: FULL_READ,
        ElementEnum.COMMENTS.value: FULL_READ,
        ElementEnum.POSTS.value: FULL_READ,
        ElementEnum.PROFILE.value: 0b00000000,
        ElementEnum.USER.value: 0b00000000,
    },
    RoleEnum.MODERATOR.value: {
        ElementEnum.ARTICLE.value: FULL_READ,
        ElementEnum.COMMENTS.value: FULL_READ | DELETE_ALL,
        ElementEnum.POSTS.value: FULL_READ | DELETE_ALL,
        ElementEnum.PROFILE.value: FULL_READ,
        ElementEnum.USER.value: READ,
    },
    RoleEnum.USER.value: {
        ElementEnum.ARTICLE.value: FULL_READ | CREATE | UPDATE | DELETE,
        ElementEnum.COMMENTS.value: FULL_READ | CREATE | UPDATE | DELETE,
        ElementEnum.POSTS.value: FULL_READ | CREATE | UPDATE | DELETE,
        ElementEnum.PROFILE.value: FULL_READ | CREATE | UPDATE | DELETE,
        ElementEnum.USER.value: READ | UPDATE | DELETE,
    },
}


def populate_data(apps, schema_editor):
    ElementModel = apps.get_model('authorization', 'Element')
    RoleModel = apps.get_model('authorization', 'Role')
    PermissionModel = apps.get_model('authorization', 'Permission')

    roles = RoleModel.objects.all()
    elements = ElementModel.objects.all()

    permissions = []
    for r in roles:
        for e in elements:
            permission = PERMISSIONS[r.name][e.name]
            permissions.append(
                PermissionModel(
                    element=e,
                    role=r,
                    read_permission=(permission & READ) != 0,
                    read_all_permission=(permission & READ_ALL) != 0,
                    create_permission=(permission & CREATE) != 0,
                    update_permission=(permission & UPDATE) != 0,
                    update_all_permission=(permission & UPDATE_ALL) != 0,
                    delete_permission=(permission & DELETE) != 0,
                    delete_all_permission=(permission & DELETE_ALL) != 0,
                )
            )

    PermissionModel.objects.bulk_create(permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20251202_1356'),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop)
    ]
