# Generated by Django 5.2.8 on 2025-12-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20251204_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.element')),
            ],
        ),
    ]
