# Generated by Django 5.2.8 on 2025-12-04 16:17

from django.db import migrations

from ..enums import ElementEnum


def populate_data(apps, schema_editor):
    ElementModel = apps.get_model('authorization', 'Element')
    SpecificElementModel = apps.get_model('authorization', 'SpecificElement')
    elements = ElementModel.objects.all()

    element_instances = {
        ElementEnum.ARTICLE.value: elements.get(name=ElementEnum.ARTICLE.value),
        ElementEnum.COMMENTS.value: elements.get(name=ElementEnum.COMMENTS.value),
        ElementEnum.POSTS.value: elements.get(name=ElementEnum.POSTS.value),
        ElementEnum.USER.value: elements.get(name=ElementEnum.USER.value),
    }

    PostModel = apps.get_model('posts', 'Post')
    PostCommentModel = apps.get_model('posts', 'Comment')
    ArticleModel = apps.get_model('article', 'Article')
    ArticleCommentModel = apps.get_model('article', 'Comment')
    UserModel = apps.get_model('users', 'User')

    objects = [
        (ArticleModel, ElementEnum.ARTICLE.value),
        (ArticleCommentModel, ElementEnum.COMMENTS.value),
        (PostModel, ElementEnum.POSTS.value),
        (PostCommentModel, ElementEnum.COMMENTS.value),
        (UserModel, ElementEnum.USER.value)
    ]

    element_objects = []
    for obj, obj_type in objects:
        element_objects.append(
            SpecificElementModel(
                name='{}.{}'.format(obj._meta.app_label, obj._meta.model_name),
                element=element_instances[obj_type],
            )
        )

    SpecificElementModel.objects.bulk_create(element_objects)


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_specificelement'),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop)
    ]
