# Generated by Django 5.2.8 on 2025-12-05 17:20

from django.db import migrations

from authorization.enums import RoleEnum
from ..utils import make_password


USERS = {
    'ADMIN': [RoleEnum.ADMIN.value],
    'USER1': [RoleEnum.USER.value],
    'USER2': [RoleEnum.USER.value],
    'EDITOR': [RoleEnum.EDITOR.value],
    'USER_EDITOR': [RoleEnum.USER.value, RoleEnum.EDITOR],
    'MODERATOR': [RoleEnum.MODERATOR.value],
    'USER_MODERATOR': [RoleEnum.USER.value, RoleEnum.MODERATOR.value],
    'USER_MODERATOR_EDITOR': [RoleEnum.USER.value, RoleEnum.MODERATOR.value, RoleEnum.EDITOR.value],
    'GUEST': [RoleEnum.GUEST.value],
}


def populate_data(apps, schema_editor):
    UserModel = apps.get_model('users', 'User')
    UserRoleModel = apps.get_model('users', 'UserRole')
    RoleModel = apps.get_model('authorization', 'Role')

    roles = RoleModel.objects.all()
    roles_map = {
        RoleEnum.ADMIN.value: roles.get(name=RoleEnum.ADMIN.value),
        RoleEnum.EDITOR.value: roles.get(name=RoleEnum.EDITOR.value),
        RoleEnum.GUEST.value: roles.get(name=RoleEnum.GUEST.value),
        RoleEnum.MODERATOR.value: roles.get(name=RoleEnum.MODERATOR.value),
        RoleEnum.USER.value: roles.get(name=RoleEnum.USER.value),
    }

    users = []
    user_roles = []
    for user_name, role_list in USERS.items():
        user = UserModel(
            first_name=user_name,
            email=f'{user_name.lower()}@test.com',
            password=make_password('password'),
        )
        users.append(user)
        user_roles += [UserRoleModel(user=user, role=roles_map[r]) for r in role_list]

    UserModel.objects.bulk_create(users)
    UserRoleModel.objects.bulk_create(user_roles)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active'),
        ('authorization', '0002_auto_20251202_1356')
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop)
    ]
